### ISSUE TITLE
Navigation on Mobile 

### ISSUE THREAD

**Issue by samdervis** [ovac/ovac-couscous-template#2]
There is no way to navigate on mobile browsers. THe sidebar navigation is completely lost and no way to even toggle.

See http://mobile-money.dervisgroup.com or screenshot below

![image](https://user-images.githubusercontent.com/25820084/38453917-16bd597a-3a66-11e8-9caf-1f64d9a8e77e.png)

**Comment by ovac** [comment]
Ok. I will look into this today.

**Comment by samdervis** [comment]
any updates?

**Comment by samdervis** [comment]
I have waited for updates for long and i have given up on this template. See how this new template looks like.
 [New documentation](https://mobile-money.samerior.com)
